name: splashpay
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1
  get: 4.6.5
  pin_code_fields: ^7.4.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  qr_code_scanner: ^1.0.1
  dotted_line: ^3.1.0
  ticket_widget: ^0.0.1
  dotted_border: ^2.0.0+2
  syncfusion_flutter_charts: ^20.1.59
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Satoshi
      fonts:
         - asset: assets/fonts/Satoshi-Regular.otf
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic