import '../data/images_path.dart';

enum TransactionType { income, expenses, done, onProgress }

class Transaction {
  String image;
  String name;
  String date;
  String status;
  double money;
  TransactionType transactionType;
  Transaction(
      {required this.image,
      required this.name,
      required this.date,
      required this.status,
      required this.money,
      required this.transactionType});
}

List<Transaction> listOfTransaction = [
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 13.23,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kSmari,
      name: 'Smari',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 7.09,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kSaira,
      name: 'Saira',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 68.09,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kKelly,
      name: 'Kelly',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 544.7,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kSam,
      name: 'Sam',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 100,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 13.23,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 13.23,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kSmari,
      name: 'Smari',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 7.09,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kSaira,
      name: 'Saira',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 68.09,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kKelly,
      name: 'Kelly',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 544.7,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kSam,
      name: 'Sam',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 100,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 13.23,
      transactionType: TransactionType.expenses),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Income',
      money: 13.23,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSmari,
      name: 'Smari',
      date: '25 June, 2022',
      status: 'Income',
      money: 7.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSaira,
      name: 'Saira',
      date: '25 June, 2022',
      status: 'Income',
      money: 68.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kKelly,
      name: 'Kelly',
      date: '25 June, 2022',
      status: 'Income',
      money: 544.7,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSam,
      name: 'Sam',
      date: '25 June, 2022',
      status: 'Income',
      money: 100,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Income',
      money: 13.23,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSmari,
      name: 'Smari',
      date: '25 June, 2022',
      status: 'Income',
      money: 7.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSaira,
      name: 'Saira',
      date: '25 June, 2022',
      status: 'Income',
      money: 68.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Income',
      money: 13.23,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kKelly,
      name: 'Kelly',
      date: '25 June, 2022',
      status: 'Income',
      money: 544.7,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Income',
      money: 13.23,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSmari,
      name: 'Smari',
      date: '25 June, 2022',
      status: 'Income',
      money: 7.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSaira,
      name: 'Saira',
      date: '25 June, 2022',
      status: 'Income',
      money: 68.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kKelly,
      name: 'Kelly',
      date: '25 June, 2022',
      status: 'Income',
      money: 544.7,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSam,
      name: 'Sam',
      date: '25 June, 2022',
      status: 'Income',
      money: 100,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Income',
      money: 13.23,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSmari,
      name: 'Smari',
      date: '25 June, 2022',
      status: 'Income',
      money: 7.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kSaira,
      name: 'Saira',
      date: '25 June, 2022',
      status: 'Income',
      money: 68.09,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kArsalSamir,
      name: 'Arsal samir',
      date: '25 June, 2022',
      status: 'Income',
      money: 13.23,
      transactionType: TransactionType.income),
  Transaction(
      image: CustomAssets.kKelly,
      name: 'Kelly',
      date: '25 June, 2022',
      status: 'Income',
      money: 544.7,
      transactionType: TransactionType.income),

// done list data
  Transaction(
      image: CustomAssets.kKiara,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 23.23,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kSiza,
      name: 'Siza',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 23.23,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kSameerElen,
      name: 'Sameer Elen',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 23.23,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kKiara2,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 33.13,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kJoshi,
      name: 'Joshi',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 20.73,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kKiara,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 23.23,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kSiza,
      name: 'Siza',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 23.23,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kSameerElen,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 23.23,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kKiara2,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 33.13,
      transactionType: TransactionType.done),
  Transaction(
      image: CustomAssets.kJoshi,
      name: 'Joshi',
      date: '25 June, 2022',
      status: 'Expenses',
      money: 20.73,
      transactionType: TransactionType.done),

//OnProgress List
  Transaction(
      image: CustomAssets.kSiza,
      name: 'Siza',
      date: '25 June, 2022',
      status: 'Income',
      money: 23.23,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kSameerElen,
      name: 'Sameer Elen',
      date: '25 June, 2022',
      status: 'Income',
      money: 23.23,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kKiara2,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Income',
      money: 33.13,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kJoshi,
      name: 'Joshi',
      date: '25 June, 2022',
      status: 'Income',
      money: 20.73,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kKiara,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Income',
      money: 23.23,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kSiza,
      name: 'Siza',
      date: '25 June, 2022',
      status: 'Income',
      money: 23.23,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kSameerElen,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Income',
      money: 23.23,
      transactionType: TransactionType.onProgress),
  Transaction(
      image: CustomAssets.kKiara2,
      name: 'Kiara',
      date: '25 June, 2022',
      status: 'Income',
      money: 33.13,
      transactionType: TransactionType.onProgress),
];
